name: Deploy to Test Instance

on:
  push:
    branches:
      - "release/*"
  pull_request:
    types: [ closed ]

jobs:
  merge-job:
    name: Merge - ${{ github.ref }} to Staging
    if: github.event.pull_request.merged == true && ${{ github.event.pull_request.base.ref == 'development' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'staging'
          commit_message_template: '[Automated] Merged {source_ref} into {target_branch}'
      - run: |
          echo PR #${{ github.event.number }} has been merged. 
          echo PR target branch ${{ github.event.pull_request.base.ref }}
          echo PR source branch ${{ github.event.pull_request.head.ref }}
          
  security:
    name: Security - Finding Vulnerabilities
    runs-on: ubuntu-latest
    needs: merge-job
    steps:
      - uses: actions/checkout@master
      - name: Run Synk to check for vulnerablities
        uses: snyk/actions/node@master
        continue-on-error: true
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

  push-build:
    name: Push build to test to Argocd
    runs-on: ubuntu-latest
    needs: security
    steps:
      - uses: actions/checkout@v1
        continue-on-error: true
      - name: Pushing test build to Argocd K8
        run: |
          echo "stage is incomplete"

